name: canon_example
description: Minimal example of the canon navigation package.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  canon: ^0.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.15.0
  canon_generator: ^0.1.0
  flutter_test:
    sdk: flutter
